# Tell Travis we need a copy of docker running
# Build our image using Dockerfile.dev
# Tell Travis how to run our test suite
# Tell travis how to deploy our code to AWS

sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t hadi207/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hadi207/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker-React"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-509893050594"
  bucket_path: "Docker-React"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"
